services:
  - type: web
    name: fconline-render
    runtime: node
    rootDir: apps/fconline
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NEXON_API_KEY
        sync: false
